language: node_js
os: osx
node_js:
  - 8
cache: yarn
script:
  - yarn test
  - yarn run build
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true,
  keep-history: true,
  github_token: $GITHUB_TOKEN
  on:
    branch: master